project 'KakaoPaySubject.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KakaoPaySubject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KakaoPaySubject

  target 'KakaoPaySubjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KakaoPaySubjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Alamofire'
  pod "SwiftSpinner"

end
